### ISSUE TITLE
Database for Sonde raw data

### ISSUE THREAD

**Issue by dj1an** [oe5hpm/dxlAPRS#1]
To analyze and visualize Weathersonde raw data like Positon, Height, Temperature etc. it would be nice to have some sort of Database connection for sondeudp/sondemod.

We are running an multi-rx SDR Weathersonde Receiver and Tracking via APRS works really well. 
To gain more Data Points, especially while Landing, we can not rely on APRS System. Logs showed, that after the very last Datapoint sended to APRS, the decoding of Position Data was going on for a few Seconds. 

Right now we are parsing the Logfiles to display actual Data on a local Website. Having the Datapoints in a Database would be so much easier.

Thanks in advance
DJ1AN, Jan

**Comment by oe5hpm** [comment]
Why we cannot rely on the data generated for the APRS system ? sondemod can be configured to output every single packet as AXUDP frame.
The RS92 devices sends every second one paket.

**Comment by dj1an** [comment]
Of cause we are connecting sondeudp and sondemod with axudp. Works really well. 
Sure, Sondemod can be configured with the low-altitude options to send more packets at lower height but as far as you go under 5 seconds aprs.fi is complaining and rate-limiting the data. A standalone Client would not have this issues, of cause.

There is a need for some historical data. Without knowing the Sonde ID you are not able to get position Data from last decoded flights. Having everything in a local Database would make things like this very easy.

**Comment by oe5hpm** [comment]
i think you don't need aprs.fi at all.
Why don't use aprsmap as viewer ? 
Hre is all received data stored as simple ascii file (rawlog), further you can save there a single track into specific file if needed. Also log replay is possible.

With some shell-scripting i think it also should be possible to track the rawlog, filter for the wanted id and generate some database commands.

**Comment by dj1an** [comment]
aprsmap is a great tool for home use, indeed.
At this time, SDR rx and decode is running on a headless Server at our rx site. 
I am very happy to got rid of our old Sondemonitor and xvfb with wine setup for decoding. I really don't want to add the graphical component at all.

How about just querying a local webserver with data you already write in the sondemod verbose log? So you don't have to implement the database thing. Something like just opening an local url like:
http://localhost/tracking.php?id=L1234567&timestamp=....&lat=...&lon=.... 
This would be much easier to implement and keeps things modular without additional compile dependencies.

**Comment by dj1an** [comment]
...is now done via log parsing script

**Comment by oe5hpm** [comment]
Perfect!
