### ISSUE TITLE
Compile on X86_64

### ISSUE THREAD

**Issue by pedda4711** [oe5hpm/dxlAPRS#11]
I've some trouble compiling the src on X86_64  (fedora based)
To compile i edit the Makefile  and set following:

 In the x86_64 specific section:
 #x86_64 specific 
 else ifeq ($(HOSTARCH), x86_64)
 XLIBS           =        -lXext -lX11 -lz -ljpeg -lpng
 CFLAGS          += -m64
 LFLAGS          += -m64

--------------------------------------------------------------------------------

Then all tools compile with some warnings

Greetings, Peter, DB1OFH

**Comment by oe5hpm** [comment]
hi peter,
and does the stuff run without any issue?

Today the code only runs with 32bit wide variables.
This is since this C-code is a translation of a modula 2 project and during the old days of modula 2 there was only 32bit machines available to "normal" people.

best 73,
Hannes - OE5HPM

**Comment by pedda4711** [comment]
Hello Hannes,

yes it works

73' Peter, DB1OFH

**Comment by oe5hpm** [comment]
we now converted the code for building / running on ia64 hosts without the need of i386 compatbile libs and tricks.

cheers,
Hannes

**Comment by dl9rdz** [comment]
Servus Hannes,

super, schaut gut aus :-)
Auf MacOS braucht es in pngread.c noch #include <stdint.h> sonst kennt er das int32_t ned.

73, Hansi, dl9rdz

**Comment by oe5hpm** [comment]
Servus Hansi,

danke fürs testen. Das fehlende include hab ich noch dazu gem8.
Dann hamma vorerst mal einigermaßen sauberen Stand.

73,
hpm

mfG
Schmelzer Hannes
