### ISSUE TITLE
Compiling error.

### ISSUE THREAD

**Issue by sp3wxh** [oe5hpm/dxlAPRS#14]
I have installed the recommended library. During compilation I have an error:

```
gcc: error: lib_x86/libz.a: Nie ma takiego pliku ani katalogu
gcc: error: lib_x86/libjpeg.a: Nie ma takiego pliku ani katalogu
Makefile:263: polecenia dla obiektu 'aprsmap-static' nie powiodły się
make: *** [aprsmap-static] Błąd 1
rafszk@sp3wxh:~/dxlAPRS/src$ 
```

**Comment by oe5hpm** [comment]
Hi,
is your host-system 32bit or 64bit ? (uname -a)
do you have latest master?

73,
hannes

**Comment by oe5hpm** [comment]
i just made some changes to the Makefile, pls try.

73,
hpm

**Comment by sp3wxh** [comment]
Hi.

Now it is working :-)
