### ISSUE TITLE
Decoding of DFM type Weathersonde

### ISSUE THREAD

**Issue by dj1an** [oe5hpm/dxlAPRS#2]
Besides the SGP Weathersondes, in Germany the DFM ones are quite popular.
May it be possible to integrate DFM Sonde Decoding in sondeudp / sondemod?

Seems easier as SGP decoding because no ephemeris Data and Position Calculation is needed.

Code is ready for Linux on:
https://github.com/rs1729/RS/tree/master/dfm
https://www.amateurfunk.uni-kl.de/projekte-aktivitaeten/decoder-wettersonden/

Thanks in advance,
DJ1AN, Jan

**Comment by oe5hpm** [comment]
Unfortunately we actually don't have such "wx-sondes" here for testing some Implementation.
Of course this would be very interesting.
I will trigger Chris, OE5DXL to have a look on the shown codebase.
Maybe we can get any peace of hardware from anywhere and implement the decoding.

**Comment by dj1an** [comment]
If you need a wav recording i can send you one. 
Also i could provide a physical DFM Sonde in Hardware if needed.

**Comment by oe5hpm** [comment]
That would be great.
Please attach the wave-file ... this should be enough for implementing.
Later, once a testversion is available, it would fine if you could run tests with real life hardware.

**Comment by dj1an** [comment]
Thanks for considering this issue. I will do so when i am at home this afternoon.

**Comment by oe5hpm** [comment]
there is some support for this type of radiosonde since commit:
https://github.com/oe5hpm/dxlAPRS/commit/1f9722866572928531a3b1575d8c27374f02a615

best 73,
Hannes
