### ISSUE TITLE
latest commit seems to not work on RaspberryPI 1,2,3

### ISSUE THREAD

**Issue by ok2it** [oe5hpm/dxlAPRS#22]
Hi,

tried to git clone   and make from scratch (all libs needed included) and all bin files were compiled ok.
When sondeudp is launched it detects correct channel numbers.
sdrtst though seems to be getting constantly about 30dB signal regardless on how many signals sources I define in config-file for rtl_tcp

Now we seem to have now 5 independent raspberries where new compiled toolchain doesnt decode any sondes at all.
(we only use sondeudp as we do RAW decoding on server side)
Jiri 73

**Comment by oe5hpm** [comment]
Hi Jiri,
thanks for reporting this.
Can you provide more informations ? (cmdline, cfg-files)
We must be able to get a reproduceable setup for debugging this.

In the meantime i will try (time is the thing ;-) to setup some receiver with rtl sdr and look for some signals.

73,
hannes

**Comment by ok2it** [comment]
Sure. I am discussing possibility to create an ssh account and access for you on one of the setups - rtl-sdr with connected antenna - otherwise working fine on x86 32/64 architecture.
If no-one is available I will re-create one and send you access...

in the meanwhile, startup script:
(lastly it launches javascript which just takes UDP RAW data, adds login details and forwards them onto another IP : PORT )


#!/bin/bash
echo "-Killing previous stuff"
killall sdrtst
killall sondeudp
killall rtl_tcp
killall rtl_sdr
killall node
killall screen
echo "-Start rtl_tcp"
screen -S rtl_tcp -d -m
screen -r rtl_tcp -X stuff "rtl_tcp -a 0.0.0.0 -p 2222 -g 5
"
sleep 1
echo "-Start sdrtst"
screen -S sdrtst -d -m
screen -r sdrtst -X stuff "/home/$USER/dxlAPRS/src/sdrtst -t 127.0.0.1:2222 -c /home/$USER/Sondy/conf.conf -v -s /home/$USER/Sondy/channels.fifo -i 2400000
"
sleep 1
echo "-Start sondeudp"
screen -S sondeudp -d -m
screen -r sondeudp -X stuff "/home/$USER/dxlAPRS/src/sondeudp -f 16000 -l 128 -c 0 -o /home/$USER/Sondy/channels.fifo -v -u 127.0.0.1:3002
"
sleep 1
echo "-Start st-uploader"
screen -S st-uploader -d -m
screen -r st-uploader -X stuff "cd /home/$USER/Sondy;node st-uploader-kryo.js
"
echo "DONE"

**Comment by ok2it** [comment]
New RTL drivers for ARM fix this. Closing.
