### ISSUE TITLE
sondemod APRS output reports wrong position

### ISSUE THREAD

**Issue by Luceoria** [oe5hpm/dxlAPRS#24]
Issue: Node which is in western hemisphere, is showed with "E".

https://github.com/oe5hpm/dxlAPRS/blob/5868e437ea72f0ec879813d63aa7173f106b12b4/src/sondeaprs.c#L434

Instead of 
`if (lat>=0.0) b[i] = 'E';`

should be:
`if (long0>=0.0) b[i] = 'E';`

Correct me if I'm wrong.

**Comment by oe5hpm** [comment]
Yeah, your'e right. We are going to fix this.
Thanks!
