### ISSUE TITLE
copy+paste doesn't work anymore on aprsmap 0.72

### ISSUE THREAD

**Issue by iKoze** [oe5hpm/dxlAPRS#25]
A Segfault appears if you try to paste something in a textbox.

**Comment by oe5hpm** [comment]
hi florian,

just merged the PR from dl9rdz, he made some fix for this.
c/p is now working here. On my machine i just couldn't pase instead of crashing.

cheers,
Hannes

**Comment by iKoze** [comment]
Hi Hannes,

thank you. It works again.
