### ISSUE TITLE
Display own GPS position in aprsmap

### ISSUE THREAD

**Issue by rs41dominik** [oe5hpm/dxlAPRS#28]
Hi!

first of all, great job with this dxlAPRS!

I have a question regarding the display of my own GPS position in aprsmap.

I have a GPS mouse connected via USB and with help of gps2aprs i am receiving my GPS position inside of aprsmap. If i click on the decoded data sentences inside of the "Monitor" a cross shows my correct GPS position, but only for about 15 seconds, then it vanishes

Is it somehow possible to configure it to show the position constantly, maybe with the car icon or with the cross?

Is it also possible to add a track for my own GPS position showing my path i have been driving on the road?

Thank you very much!
Best regards,
Dominik

**Comment by oe5hpm** [comment]
Hi Dominik,

for sure, this is possible. You're already on the right track with "gps2aprs".

use `-i "/>"` for having a car as symbol

use `-N 127.0.0.1:9001` for posting every 2 seconds a beacon to your local aprsmap (ip and port depends on your aprsmap configuration)

Maybe you can post your full commandline of gps2aprs if somethin isn't working and we can analyze that.

cheers,
Hannes

**Comment by rs41dominik** [comment]
Hi Hannes,

thank you for your fast reply!

Here is the command line i use for gps2aprs:
./ gps2aprs -a -I Auto -t /dev/ttyUSB0:4800 -v -N 127.0.0.1:9002 -i "/>"

My GPS position is correctly transmitted to aprsmap, but it displays on the map only when clicking the decoded line in the Monitor (and then only for 10-15 seconds).

I am using RF port 1 inside of aprsmap and no further beacon configuration or things like that.

Do i have to do some other configuration inside of aprsmap directly to display the position and track continuously?

Thank you and ciao,
Dominik

**Comment by oe5hpm** [comment]
HI,

commandline looks good.
Maybe the callsign "Auto" is a problem.
Try to switch off the callcheck in aprsmap "Config -> RF-Ports"

cheers,
hannes

**Comment by rs41dominik** [comment]
Hey,

perfect! 

The callcheck was the problem.
It now displays the car icon at my position constantly and even the track.

Thank you very much and have a nice evening!
Dominik

**Comment by oe5hpm** [comment]
glad to hear.
