### ISSUE TITLE
Display decoded RS41 inside aprsmap

### ISSUE THREAD

**Issue by rs41dominik** [oe5hpm/dxlAPRS#29]
Hi!

I would ask you to please help me setting up the configuration of udpgate4 for displaying a decoded rs421 sonde inide aprsmap.

Everything is working fine, thanks to OE1FFS and his instruction of how to set up everything. SONDEMOD is showing the decoded data, but the last step with udpgate4 of streaming the data to an RF Port of aprsmap is not working so far.

Here is my command line for udpgate4:
xfce4-terminal --title UDPGATE4 -e 'bash -c "udpgate4 -S Raspi -M :0/9201"'

Do i need to define additional command line arguments?

Thank you very much!
Dominik

**Comment by oe5hpm** [comment]
hi dominik,
udpgate4 has nothing todo with decoding and displaying weather sondes on a local machine.

updgate4 is an aprs igate server.

the chain for your challenge is:

sondeudp --> sondemod --> aprsmap

here's the commandline snippet for sondemod
 `-r <ip>:<port> send AXUDP -r 127.0.0.1:9001 use udpgate4 or aprsmap as receiver`

cheers,
Hannes

**Comment by rs41dominik** [comment]
Hi Hannes,

thanks a lot for your fast help again!

I tried as you told me, but it won´t work so far.

Here is my command line for sondemod:
xfce-terminal --title SONDEMOD -e 'bash -c "sondemod -o 18000 -I ABCDEF-12 -r 127.0.0.1:9001 -b 20 -B 6 -A 1500 -x /tmp/e.txt -R 240 -d -p 2 -v"'

In aprsmap i configured RF Port 1 as following:
:0:9001

aprsmap is telling me UPD1 open, but the symbolic "1" stays with a red background.

Maybe some issue with the callsign again? What to do with the callsign if i do not have one?

Vielen Dank!
Dominik

**Comment by rs41dominik** [comment]
Hi,

i cannot tell you what i did but it works now, exactly with the command line of the post above.

Thank you very much!
Dominik
