### ISSUE TITLE
Use of APRS Status Field

### ISSUE THREAD

**Issue by dj1an** [oe5hpm/dxlAPRS#3]
Right now, the APRS Status Field seems unused for udpgate beacon messages and Packages generated by sondemod. Would be a nice-to-have.

Documentation can be found at:
http://www.aprs.org/doc/APRS101.PDF 
on Page 80

Thanks in advance,
DJ1AN, Jan

**Comment by oe5hpm** [comment]
Hi Jan,
i don't see the use-case to the "status-report" which things there should be reported?

best regards,
Hannes

**Comment by dj1an** [comment]
An additional free configurable Text, like option -t does already but not adding text to the position report comment field

**Comment by oe5hpm** [comment]
the position report is already included in the APRS frame. 
Would end up in redundant data ?

**Comment by oe5hpm** [comment]
due to inactivity i close this issue for now.
