### ISSUE TITLE
APRS Data on aprsmap

### ISSUE THREAD

**Issue by rs41dominik** [oe5hpm/dxlAPRS#30]
Hi,

i am asking for help regarding the following issue: i try to display aprs online data on aprsmap, i tried didfferent servers like:

- euro.aprs2.net
- germany.aprs2.net
- austria.aprs2.net

Aprsmap shows me with the green "N" that i am connected to the server, but the monitor and the map itself do not display any data.

I entered a callsign, my symbol and my position inside of the config menu, but i do not have a passcode and i only want to Rx data.

I am interested in displaying radiosonde related data.

I would appreciate your help, thank you!
Dominik

**Comment by oe5hpm** [comment]
HI dominik,

i would tip on a missing "serverfilter", such big server have no default filter.
Try to provide a "m/200" filter, this would tell the server giving you data with a radius of 200km of your position.

cheers,
Hannes

**Comment by rs41dominik** [comment]
Hi Hannes,

and thanks for your replay.

I also tried different serverfilter settings, m/200, m/500, m/1000, but unfortunately nothing works.

After connecting to germany.aprs2.net on default port and waiting 1 minute, hovering the mouse over the green "N" is telling me i received 7 rx frames and 470 rx bytes, istnt that pretty few?

Monitor is also not displaying any raw data frames.

I tried it on windows pc and also on my raspberry, both times the same issue.

Thanks for your help!
Dominik

**Comment by oe5hpm** [comment]
hi,
just tried it here ... works without any issue.

maybe a problem with your call-sign or position.
whats the call you're using?

cheers,
Hannes

**Comment by rs41dominik** [comment]
Hi,

as i do not have a real callsign, i just entered some fake callsign "RASPID". Does this make any problem?

My position is correctly set.

Ciao,
Dominik

**Comment by oe5hpm** [comment]
hi dominik,

maybe the right point for getting a real callsign ;-) just kidding. but it' very interesting stuff.

I tried also connecting with "RASPID", without an issue ... at the moment no idea. Will go on thinking about ... 

cheers,
Hannes

**Comment by rs41dominik** [comment]
Hm ok, interesting:D

Maybe the issue is within my home network / router configuration blocking data of the port.

I keep you up to date!

Thanks,
Dominik

**Comment by rs41dominik** [comment]
Hi,

i told you i will keep you up to date, i have news:

A friend and me got it working finally the following way:
- own 'My CALL' is set
- If 'My Position' is set or not does not make any difference
- 'Server url' works with e.g. 'germany.aprs2.net:14580'
- and the most important thing: 'Serverfilter' is set like: 'r/48.9/12.6/200'

Perhaps this may be helpful to others as well!

Greets,
Dominik

**Comment by oe5hpm** [comment]
since the facts are clear since may this year, i'll close this issue.
