### ISSUE TITLE
sondemod: calibration lost when RS-92 sondes received simultaneously

### ISSUE THREAD

**Issue by Wojtus11** [oe5hpm/dxlAPRS#31]
When two different RS-92 sondes are decoded at the same time, calibration data is lost (reset to zero) for both of them. Filtered log to illustrate:
[sondemod_twoRS92_bug_short.log](https://github.com/oe5hpm/dxlAPRS/files/1977626/sondemod_twoRS92_bug_short.log)

Full log:
[sondemod_twoRS92_bug.log.gz](https://github.com/oe5hpm/dxlAPRS/files/1977635/sondemod_twoRS92_bug.log.gz)

**Comment by oe5hpm** [comment]
hi wojtus,

you're first reporting this issue under many sonde receievers.
Our expection is that the calibration file couldn't be written in your cwd (current work dir).

For checking this we've introduced a error message regarding this. please try the latest commit.

cheers,
Hannes

**Comment by Wojtus11** [comment]
Yes, my filesystem is read-only (by purpose, to protect SD card). I have now changed working directory to /tmp. Unfortunately bad winds this night to catch both Prostejov and Poprad. I will keep you informed.

**Comment by Wojtus11** [comment]
OK, checked and confirmed - this was caused by lack of write access to CWD. Issue closed :)
