### ISSUE TITLE
Compiling Hints for ARM

### ISSUE THREAD

**Issue by OE5DRO** [oe5hpm/dxlAPRS#32]
In the compiling hints for C-Sources is a little correction needet:
The X in libx11-dev and  libxext-dev MUST be lowercase.
If not, they are not found on ARM (RPi):

build for X86 with i386 (32-bit) host system
or
build on some native ARM machine (like raspbian on rpi)
=========================================
install following packages:
- build-essential  (sudo apt-get install build-essential)
- libX11-dev       (sudo apt-get install libX11-dev)    <===
- libXext-dev      (sudo apt-get install libXext-dev)  <===
- libpng-dev       (sudo apt-get install libpng-dev)
- libjpeg-dev      (sudo apt-get install libjpeg-dev)

make all

**Comment by oe5hpm** [comment]
thanks for reporting this.
just fixed this.

cheers,
Hannes #
