### ISSUE TITLE
dxlAPRS and GPS receivers

### ISSUE THREAD

**Issue by qqlele** [oe5hpm/dxlAPRS#33]
I recently had a ham radio presentation in Rabat, Morocco. I had with
me a simple GPS receiver in form of a USB mouse (a Taiwanese/Chinese
production), to perform a practical demo. (I used dxlAPRS for demo.) The
GPS receiver had been tested & proved as fully functional across Europe
as well as in mid-Asia, before I started the journey to Morocco. However,
for some unknown reason(s) it did not show my proper location in Rabat,
but instead a location some 1000-1500 km to the east (somewhere near the
border in between Algeria and Tunisia).

To confirm that the receiver was still operational, I made a test while
waiting for my returning flight in Paris, France. And the receiver was
good again there.

That experience made me wonder why the GPS position in Morocco was
reported differently (wrongly) to the positions in Europe and Asia?
Maybe the G-mouse was produced for European/Asian markets only, but not
for Africa? Generally speaking, I am unsure whether GPS products behave
differently across the globe, regarding specific satellite
constellations here and there. Or something else was the problem?

For example, I was told that usually big position error is caused by
wrong coordinate system, so that it is needed to set the coordinate
system in the mapping or surveying software before collecting data. I
wonder if there is any such "coordinate system" setup with dxlAPRS that
I missed to do?

Best regards,

Misko YT7MPB (ex-CN2MPB)

**Comment by oe5hpm** [comment]
Hi Misko,

thanks for reporting this.
We've fixed a bug fitting to your report:

https://github.com/oe5hpm/dxlAPRS/commit/e77827bccb214a84db46cc18545992a6a2104d3b

which version of the toolchain you're using?

best 73,
hannes

**Comment by qqlele** [comment]
On 06/28/2018 08:58 PM, Hannes Schmelzer wrote:

> Hi Misko,
> 
> thanks for reporting this.
> We've fixed a bug fitting to your report:
> 
> https://github.com/oe5hpm/dxlAPRS/commit/e77827bccb214a84db46cc18545992a6a2104d3b
> 
> which version of the toolchain you're using?
> 
> best 73,
> hannes
> 

Hi Hannes,

I use version dated 03 December 2016, 10:09

I noticed that the actual zip file is from 08 May 2018, 14:25
Is that one better?

Regards,

Misko

**Comment by oe5hpm** [comment]
Hi Misko,

yes - please take latest version.
As you an see in commit https://github.com/oe5hpm/dxlAPRS/commit/e77827bccb214a84db46cc18545992a6a2104d3b the fix was introduced on March 3rd this year. Maybe you've the chance for traveling to Morocco again ;-)

i will close this issue for now, if the problem still exist don't scary to reopen.

best 73,
hannes

**Comment by qqlele** [comment]
On 06/29/2018 01:59 PM, Hannes Schmelzer wrote:

> Hi Misko,
> 
> yes - please take latest version.
> As you an see in commit https://github.com/oe5hpm/dxlAPRS/commit/e77827bccb214a84db46cc18545992a6a2104d3b the fix was introduced on March 3rd this year. Maybe you've the chance for traveling to Morocco again ;-)
> 
> i will close this issue for now, if the problem still exist don't scary to reopen.
> 
> best 73,
> hannes
>   
> 

Hello Hannes,

Thank you for info. Well I also hope to travel there again. But next 
time I will not forget to check another APRS software besides dxlAPRS. 
In fact I did have DireWolf + Xastir on my laptop too, but somehow in a 
hurry I forgot to activate it to check for this GPS error.  :-)

Best 73

Misko
