### ISSUE TITLE
GeoID correction

### ISSUE THREAD

**Issue by pit711** [oe5hpm/dxlAPRS#35]
Raw GPS data is about 45m to high in Europe.
Any chance to get an GeoID correction value option to fix that?

**Comment by oe5hpm** [comment]
Hi,
chris sent some changes to me (https://github.com/oe5hpm/dxlAPRS/commit/1010212ea48c8f0588d62d7bb6cf16775bff6273) which look like something like your request.

Please have a look and report.
cheers,
Hannes

**Comment by pit711** [comment]
Exactly what we need, thanks.

**Comment by oe5hpm** [comment]
perfect. have fun with dxlAPRS.
cheers,
Hannes
