### ISSUE TITLE
Possible to display station/object no digital SSID

### ISSUE THREAD

**Issue by sp2ong** [oe5hpm/dxlAPRS#4]
Hi,

Is it possible add to display station as object which have no digital SSID.
SSID in APRS station have special importance but when we use display on APRS Map our HamNET nodes as objects for example where station is placed with the same callsign in one more place, we use symbol 88 (802.11 WLAN or other network node - http://f5vag.nerim.net/aprs/new-symbols/ ) to display HamNET objects on map with SSID:

SP1ABC-L1   (sp1abc link no 1)
SP1ABC-L2   (sp1abc link no 2)
SP1ABC-GW  (sp1abc gateway)
etc

We do not want use SSID for typical APRS stations-object.

It is not problem with aprs server which accept this SSID and map server like aprs.fi or application xastir display  our objects nodes on ampr map with this mixed chars and digital SSID but APRSMap application look that not display this stations on map.

I would like use aprsmap as base application in emcom group where we will be use HamNet network and aprs but it will be nice to see on apremap our hamnet objects too with not typical SSID

**Comment by oe5hpm** [comment]
Yes i think this should be possible.

Did you already play around with "Config -> RF-Ports -> Beacon + Objects" ?
There you can define multiple objects without "real SSID".

Tip: the position of the object can be altered with SHIFT + click left on the map.

Please give me feedback if this is useful your you.

best 73,
Hannes - OE5HPM

**Comment by sp2ong** [comment]
Hi,

I don't want send object from aprsmap but APRSmap don't display objects where exist on aprs.fi map

Look on:

http://aprs.fi/#!lat=53.015&lng=18.600&z=16&mt=terrai0

you can see hamnet objects: SP2PMK-L1, SP2PMK-L2 , SP2PMK-GW 

Please try to move n aplication  APRSMap on this position and can you see this objects ???

but on APRSMap this object are not displayed it look like APRSmap don't display any object which SSID is not digital form.

73 Waldek SP2ONG

**Comment by oe5hpm** [comment]
hi waldek,
just pushed a new version, where changes happend on this. can you try and report?
best regards,
HAnnes

**Comment by sp2ong** [comment]
Hi Hannes,

Thank you for new version I have see new icons connected with WIFI HamNET Nodes (thank you)
but still I can not see objects SP2PMK-L1, SP2PMK-L2 and SP2PMK-GW on aprsmap
I have use latest aprsmap v0.61 under linux complied by you 26 May

73 Waldek

**Comment by oe5hpm** [comment]
from where did you download ? dxlaprs.hamspirit.at ?
if true, thats the autobuild from this sources, started one a day if new sources available.
the changes pushed up today aren't included in this build ... you can build the sources by your own or wait until tomorrow for the autobuild.

best 73,
hannes

**Comment by sp2ong** [comment]
I have download from this url:
http://oe5dxl.ampr.at/aprs/osm-mapper/bin/
and get aprsmap-i386.tgz

**Comment by sp2ong** [comment]
By the way I have try to set brightens map, objects etc but it maybe in future change more visibility icons on map but it is look like are very small or others (if we compare to aprs.fi displayed icons)
What you think,  is it make sense change size icons or make more visible ?

73 Waldek

**Comment by sp2ong** [comment]
Hi,

I have download sources and compiled own version under Ubnutu 15. But still aprsmap don't display objects with SSID like L1, L2 and GW

73 Waldek

**Comment by oe5hpm** [comment]
Hi waldek,
the URL http://oe5dxl.ampr.at/aprs/osm-mapper/bin/ is also valid.
This one is hosted directly at OE5DXL, the maintainer of aprsmap.

I will talk to chris, oe5dxl, regarding this issue and give you update.
best 73,
hannes

**Comment by sp2ong** [comment]
Hi Hannes

How's the progress with the solution of my problem ?

73 Waldek

**Comment by oe5hpm** [comment]
Hi Waldek,

i've discussued this topic again with chris.
The standard says, that only numeric 0-15 can take place in SSID - everything else is against the APRS standard.
The fact that your actual configuration is working is a piece of luck and servers who don't check the standard fully.

However, why you don't draw items/object onto the aprs map which are showing your hamnet link and so on ? Also things like FM-Repeaters are drawn this way.

Did you have had a look into "Config -> RF-Ports -> Beacon + Objects" ?
For my understanding you can achieve your wishing exactly with this.

best regards,
Hannes

**Comment by sp2ong** [comment]
Hi,

I do not need to send objects with nonstandard SSID via APRSMap. I want to display on APRSMap objects with nonstandard SSID like I can do with Xastir application. It is not problem with XASTIR but I would like recommended APRSmap in our local area to use instead XASTIR . Please try XASTIR and move map close to my area and you can see on XASTIR map our Hamnet objects with nonstandard map. I can see this objects via http://aprs.fi/#!lat=53.015&lng=18.630&z=13&mt=terrain
but in this case I must have access to internet to display map

Sorry but it is not clear for my:

> Did you have had a look into "Config -> RF-Ports -> Beacon + Objects" ?

Do you suggest that I can manually display all nonstandard SSID object via this option ????
If yes,  all local hamradio who want use APRSMap must do this to display which is exist in APRS database ???

73 
Waldek

**Comment by oe5hpm** [comment]
Hi Waldek,

no.
"Config -> RF-Ports -> Beacon + Objects" is used to send your own objects with correct standard.

I will talk to chris for implementing an exception against aprs standard for displaying non standard things, probably with some switch "display all non protocol-standard" things.

best 73,
hannes

**Comment by sp2ong** [comment]
Hi Hannes,

Thank you very much for find solution like switch  "display all non protocol-standard" . It will be useful solution.

73

Waldek

**Comment by oe5hpm** [comment]
hi waldek,

there is a button in config -> rfports -> CallCheck
make sure that is turned off, so you will see the stations with invalid ssid.

![spcallck](https://cloud.githubusercontent.com/assets/6533623/16173695/f767831a-35a9-11e6-83db-24794a84cd9c.PNG)

further be informed, that such wrong ssids only can be transported over internet / tcp. It is not possible to bring this things on air with a normal aprs radio.

So i would strongly suggest to help eliminating this and do the right, draw items/object onto screen.

**Comment by sp2ong** [comment]
Hi Hannes,

Many thanks

Waldek

**Comment by sp2ong** [comment]
Hi Hannes,

Where is available version APRMap with this new option?

73 Waldek

**Comment by oe5hpm** [comment]
Hi waldek,

the version on git or version on dxl' webspace should already have this opt.

best 73,
hannes

**Comment by sp2ong** [comment]
Hi,

Ok I have download latest github sources and recompile under linux and all working now very well.
Thanks.

By the way I have see on your screen dump that you have nice symbols HamNET object on map. But at current sources are still less visible icons :-)

73 Waldek

**Comment by oe5hpm** [comment]
hi waldek,

just pushed some new font and symbols. have a look.

best 73,
hannes
