### ISSUE TITLE
Display map center on my xy cooridinates

### ISSUE THREAD

**Issue by sp2ong** [oe5hpm/dxlAPRS#5]
It will be useful add possibility that when user put in "Config-> Online-> My position" own XY coordinates after startup application aprsmap the map will be displayed in center own position. At current after startup application I must manually move map to my local position.

**Comment by oe5hpm** [comment]
hi,

you can achieve this by doing following:

- move map to desired startup position
- click on menu 'Zoom' 
- hold the shift-key and click on the most left field just below "Zoom to Markers"

you will be informed with "View stored!"

So aprsmap comes up everytime at same position.

please let me know if this is useful for you.

best regards and 73,
hannes - oe5hpm

**Comment by sp2ong** [comment]
Hi Hannes,

Yes, it help me and working after restart aprsmap

Thanks,

73 Waldek sp2ong

**Comment by oe5hpm** [comment]
great to hear. i'll close this issue.

best 73,
hannes - oe5hpm
