### ISSUE TITLE
Add decoder to give status Burst Kill for RS41.

### ISSUE THREAD

**Issue by tomaszsa** [oe5hpm/dxlAPRS#8]
Hi.
I have modified sondemod to give info about burst kill?
My modified source files in attachment.
Sources contains my comments in my native language and are reformatted.

[burstKill.zip](https://github.com/oe5hpm/dxlAPRS/files/607567/burstKill.zip)

I have two another questions?
Why compressed aprs frame from sondemod is not send via udpgate4?
I must change it to uncompressed.
How configure pair rtltst - sondeudp when I set two or more frequencies in config for rtltst?
When I add second frequency sondeupd didn't decode any frame.

Thanks in advance for your help.
73 de SQ7BR Tomasz

**Comment by dj1an** [comment]
Hi Tomasz
Thanks for providing the BurstKill detection. Very useful!

> How configure pair rtltst - sondeudp when I set two or more frequencies in config for rtltst?
When I add second frequency sondeupd didn't decode any frame.

You need to take care, that the two Frequencies are in between 95% of your receiving Bandwidth (-i)
Don't use Parameter -m for audiochannels.
How are you transfering audio data from sdrtst to sondeudp? 
Here my setup with a fifo:
```
mkfifo multichannel.fifo
rtl_tcp -a 127.0.0.1 -p 30000 -g 40 -P 40 -d 0 -b 50
sdrtst -t 127.0.0.1:30000 -c sdrcfg.txt -k -v -s multichannel.fifo
sondeudp -f 16000 -l 128 -c 0 -o multichannel.fifo -I CALLSIGN-11 -v -u 127.0.0.1:40000
```

73 de DJ1AN, Jan

**Comment by oe5hpm** [comment]
comment from oe5dxl:

sondemod transmits uncompressed and the program part for other modes is
simply copied out of the tracker gps2aprs bit not active.
to use this part it has to be modified to build "objets" now it sends
"beacon".
i tested it and it passed through udpgate4 but then you (your call)
will fly on the heaven not an object from you.
guess, there is enough space in internet for uncompressed frames
and as you see by ok1com's touchdown-predicts, the data should be
unique and simple to read by other programs.

cheers,
Hannes

**Comment by oe5hpm** [comment]
comment from oe5dxl:

sondemod transmits uncompressed and the program part for other modes is
simply copied out of the tracker gps2aprs bit not active.
to use this part it has to be modified to build "objets" now it sends
"beacon".
i tested it and it passed through udpgate4 but then you (your call)
will fly on the heaven not an object from you.
guess, there is enough space in internet for uncompressed frames
and as you see by ok1com's touchdown-predicts, the data should be
unique and simple to read by other programs.

cheers,
Hannes

**Comment by oe5hpm** [comment]
comment from oe5dxl regarding question two:

mknod rohr p
./sondeudp -f 16000 -o rohr -I MYCALL-11 -u 192.168.1.1:18000 -c 0 -v
  with -c 0 the number of channels is detected automatic
./sdrtst -t 127.0.0.1:18100 -r 16000 -s rohr -Z 100 -c up.txt -v
  up.txt is freq table for 1 stick and frequency calibration for the stick.
  this looks like
-------------------------------------------
# p num value
# f mhz afc(khz) squelch(0..100) lowpass(0..100)
p 5 52
p 8 1

f 402.0 5 60 0 6000
f 402.3 5 70
.....
-------------------------------------------
  the first is 6khz IF-width the 2nd is 12khz
  -Z 100: closed quelch needs about 1% cpu of open squelch
  first you have to find out calibration "p 5 52" fits for my stick

cheers,
Hannes

**Comment by oe5hpm** [comment]
thomasza,

i've just pushed new source tree with your additions.
many thanks for contributing code to the project.

best 73,
Hannes - OE5HPM
